Squashed commit of the following:
commit 023b172f2f8c09d3ac1f17e76decf1143ffed5e9
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Sun Aug 16 10:03:36 2026 +0530

    fix(theme): unify local development theme setup

commit 1abedfa66d15f4255dacf945f6341e026c628ce2
Merge: ae11554 626c660
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Tue Aug 11 12:45:18 2026 +0530

    Merge remote-tracking branch 'upstream/master' into sandbox

commit ae11554ca88dce8aede001c3c53d0f8bb0eb5b9b
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Tue Aug 11 12:39:37 2026 +0530

    fix(theme): integrate colordot scotopia

    Integrate scotopia theme with colordot color indicators using
    common colorlib library.

commit 626c660f54054953e630bef85fdf65e159c7516a
Author: orip <oriori1703@gmail.com>
Date:   Fri Aug 7 18:44:41 2026 +0300

    Update the CI actions

commit b84f0b775d991de3640b752eee8cb857d4bbfe27
Author: orip <oriori1703@gmail.com>
Date:   Fri Aug 7 18:39:45 2026 +0300

    Fix CI checkout after github new security policy

    Github now fails with the following error when using
    `on: pull_request_target`:
    ```
    Error: Refusing to check out fork pull request code from a
    'pull_request_target' workflow. This workflow runs with the base
    repository's GITHUB_TOKEN, secrets, default-branch cache scope, and
    runner access. Fetching and executing a fork's code in that trusted
    context commonly leads to "pwn request" vulnerabilities. To opt in,
    review the risks at https://gh.io/securely-using-pull_request_target and
    set 'allow-unsafe-pr-checkout: true' on the actions/checkout step.
    ```

    This reverts https://github.com/nvim-lua/kickstart.nvim/pull/571
    and reopens https://github.com/nvim-lua/kickstart.nvim/pull/570

commit bd53f28e494d05dac2d699a0bb66723a0346271c
Author: orip <oriori1703@gmail.com>
Date:   Fri Aug 7 18:32:36 2026 +0300

    Fix corrupted library path of lua_ls

    The previous code accidentally overwrote the library path of lua_ls
    because it used `vim.tbl_extend` instead of `vim.list_extend`.

    Because they paths that were added to the list (`luv` and `busted`) are
    not really relevant for neovim configs, they are omitted entirely.

    fixes: #2138

commit b01d0527708d01b01c9f490dd6ad76d4f3166d0b
Author: orip <oriori1703@gmail.com>
Date:   Mon Jul 27 11:19:45 2026 +0300

    Fix lua_ls diagnostics

    fixes: #2133

commit 267fb6aa73b035ca5cc5d6b54335cafab11eed16
Merge: 216e06a 7a3532a
Author: Ori Perry <48057913+oriori1703@users.noreply.github.com>
Date:   Sat Jul 25 21:47:36 2026 +0300

    Merge pull request #2068 from stephansama/feature/update-readme-for-templating

    chore: updated readme

commit 216e06a36d25e837182e7c1dda87a14cc3455a04
Author: orip <oriori1703@gmail.com>
Date:   Sat Jul 25 20:54:30 2026 +0300

    Update section 2's name

commit 9a023810f4e2f7bac03b6d4e87d4c60b3cc60e5d
Merge: 3a2194f 3a6511c
Author: Ori Perry <48057913+oriori1703@users.noreply.github.com>
Date:   Sat Jul 25 20:51:05 2026 +0300

    Merge pull request #2093 from rez1-dev/section-names

    chore(init.lua): clarify section comments

commit 3a2194f210f6accb7afae4484149554d22b38d0a
Author: orip <oriori1703@gmail.com>
Date:   Sat Jul 25 20:44:16 2026 +0300

    Call mason-lspconfig.setup to avoid UB

    fixes: #2121, resolves: #2128

commit 7a3532ac07d7054261765854e7d72cb51db4e717
Author: stephansama <stephanrandle@hotmail.com>
Date:   Fri Jun 12 09:52:53 2026 -0400

    chore: add language for forks

commit 3a6511c71ab01a16fab14327e12f0345e58a467c
Author: rez1 <66778119+rez1-dev@users.noreply.github.com>
Date:   Fri Jun 12 14:16:40 2026 +0600

    chore(init.lua): clarify section comments

commit 2a12a5a66a13abd7cc931feb4b33d95b38f8ac79
Merge: b8732e9 f0a2108
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Thu Jun 11 21:28:14 2026 +0530

    Merge remote-tracking branch 'upstream' into sandbox

commit b8732e94559a62e8f01a0da1d70605630f4febdb
Merge: bc90fe1 ac51593 9e345b9
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Thu Jun 11 21:25:11 2026 +0530

    Merge branch 'master', remote-tracking branch 'upstream' into sandbox

commit bc90fe10cd06b57f389fb917dca6bd413bdd3b78
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Thu Jun 11 20:56:03 2026 +0530

    fix(misc): restore missing theme and options

commit c2107677348dd349ea36ebc437d1deacb28b5994
Author: Sayan Shankhari <sayan0shankhari@gmail.com>
Date:   Wed Jun 10 10:06:43 2026 +0530

    fix(test): force track test script

commit f1de74680aadccd645e178b345a09f83e7863754
Author: stephansama <stephanrandle@hotmail.com>
Date:   Thu May 28 04:07:22 2026 -0400

    chore: updated readme